name: Github action test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #  matrix:
    #    python-version: [2.7, 3.5, 3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install OAS and its dependencies
      run: |
        python -m pip install --upgrade pip wheel
        pip install .
    - name: Install pyGeo and pySpline
      run: |
        pip install mpi4py
        git clone https://github.com/mdolab/pyspline.git
        cd pyspline
        cp config/defaults/config.LINUX_GFORTRAN.mk config/config.mk
        make
        pip install -e .
        cd ..
        git clone https://github.com/mdolab/pygeo.git
        pip install -e ./pygeo
    - name: Install packages for tests and docs
      run: |
        pip install coverage coveralls testflo
        pip install --user travis-sphinx
    # - name: Lint with flake8
    #  run: |
    #    # stop the build if there are Python syntax errors or undefined names
    #    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    #    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
    #    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Run script
      run: |
        python script.py